apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: app
    image: nginx:latest
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
